/** Logical schema policy and SQL compilation. No database or execution access. */
import { createHash } from "node:crypto";
import { isDeepStrictEqual } from "node:util";
import type {
  ColumnDescriptor,
  IndexDescriptor,
  TableDescriptor,
} from "../src/schema.ts";
import {
  assertDecimalDefinition,
  assertFiniteFloat,
  assertSafeInteger,
  base64ToBytes,
  decimalToScaled,
  normalizedEnumValues,
} from "../src/values.ts";
import type { EvaluatedTable } from "./evaluator.ts";

export type Backend = "sqlite" | "postgresql";
export interface PhysicalColumn {
  name: string;
  type: string;
  nullable: boolean;
  default: string;
  primary_key: boolean;
  primary_key_position: number;
  generated: boolean;
}
export type PhysicalIndex = IndexDescriptor;
export const hash = (value: string) =>
  createHash("sha256").update(value).digest("hex");
export const quote = (value: string) => `"${value.replaceAll('"', '""')}"`;
const literal = (value: string) => `'${value.replaceAll("'", "''")}'`;
export const validColumn = (value: string) =>
  /^[a-zA-Z_][a-zA-Z0-9_]{0,62}$/.test(value);
export const validTable = (value: string) =>
  value.length <= 63 && (
    /^[a-z0-9]+(?:_[a-z0-9]+)*__[a-z0-9]+(?:_[a-z0-9]+)*__[a-z0-9]+(?:_[a-z0-9]+)*$/
      .test(value) ||
    /^[a-z0-9][a-z0-9_]{55}_[a-f0-9]{6}$/.test(value)
  );
export function checkName(table: string, column: string): string {
  const name = `${table}__${column}__check`;
  return name.length <= 63
    ? name
    : `${name.slice(0, 52)}_${hash(name).slice(0, 10)}`;
}
export function physicalType(
  backend: Backend,
  column: ColumnDescriptor,
): string {
  if (column.logical_type === "decimal") {
    assertDecimalDefinition(column.precision!, column.scale ?? 0);
  }
  const types: Record<string, [string, string]> = {
    text: ["TEXT", "text"],
    enum: ["TEXT", "text"],
    boolean: ["INTEGER", "boolean"],
    integer: ["INTEGER", "bigint"],
    decimal: ["INTEGER", "bigint"],
    float: ["REAL", "double precision"],
    datetime: ["TEXT", "timestamp with time zone"],
    bytes: ["BLOB", "bytea"],
    json: ["TEXT", "jsonb"],
  };
  const type = Object.hasOwn(types, column.logical_type)
    ? types[column.logical_type]
    : undefined;
  if (!type) {
    throw new TypeError(`unsupported logical type ${column.logical_type}`);
  }
  return type[backend === "sqlite" ? 0 : 1];
}
export function checkExpression(backend: Backend, c: ColumnDescriptor): string {
  const name = quote(c.name);
  switch (c.logical_type) {
    case "boolean":
      return backend === "sqlite" ? `${name} IN (0, 1)` : "";
    case "integer":
      return `${name} BETWEEN -9007199254740991 AND 9007199254740991`;
    case "decimal": {
      const max = "9".repeat(c.precision!);
      return `${name} BETWEEN -${max} AND ${max}`;
    }
    case "enum":
      return `${name} IN (${c.enum_values!.map(literal).join(", ")})`;
    default:
      return "";
  }
}
export function defaultSQL(backend: Backend, c: ColumnDescriptor): string {
  if (!c.default) return "";
  if (c.default.kind === "now") {
    if (c.logical_type !== "datetime") {
      throw new TypeError("defaultNow() is valid only for datetime");
    }
    return backend === "sqlite"
      ? "(strftime('%Y-%m-%dT%H:%M:%fZ','now'))"
      : "date_trunc('milliseconds', CURRENT_TIMESTAMP)";
  }
  if (c.default.kind !== "literal") throw new TypeError("invalid default kind");
  const value = c.default.value;
  switch (c.logical_type) {
    case "text":
    case "enum":
    case "datetime":
      return literal(value as string);
    case "boolean":
      return backend === "sqlite"
        ? (value ? "1" : "0")
        : (value ? "TRUE" : "FALSE");
    case "integer":
    case "float":
      return String(value);
    case "decimal":
      return decimalToScaled(value as string, c.precision!, c.scale ?? 0)
        .toString();
    case "bytes":
      return backend === "sqlite"
        ? `X'${
          [...base64ToBytes(value as string)].map((v) =>
            v.toString(16).padStart(2, "0")
          ).join("")
        }'`
        : `decode(${literal(value as string)}::text, 'base64'::text)`;
    case "json":
      return literal(JSON.stringify(value)) +
        (backend === "postgresql" ? "::jsonb" : "");
  }
}
export function columnSQL(
  backend: Backend,
  table: string,
  c: ColumnDescriptor,
  creating: boolean,
): string {
  const parts = [quote(c.name), physicalType(backend, c)];
  if (c.generated) {
    parts.push(
      backend === "sqlite" ? "PRIMARY KEY" : "GENERATED BY DEFAULT AS IDENTITY",
    );
  }
  if (!c.nullable && !(c.generated && backend === "sqlite")) {
    parts.push("NOT NULL");
  }
  if (c.default) {
    if (!creating && c.default.kind === "now") {
      throw new Error(
        `adding defaultNow() column ${c.name} requires a migration`,
      );
    }
    parts.push(`DEFAULT ${defaultSQL(backend, c)}`);
  }
  const check = checkExpression(backend, c);
  if (check) {
    parts.push(
      `CONSTRAINT ${quote(checkName(table, c.name))} CHECK (${check})`,
    );
  }
  return parts.join(" ");
}
export function createTableSQL(
  backend: Backend,
  descriptor: TableDescriptor,
): string {
  const parts = descriptor.columns.map((c) =>
    columnSQL(backend, descriptor.table_id, c, true)
  );
  if (
    (descriptor.primary_key ?? []).length &&
    !(backend === "sqlite" && descriptor.columns.some((c) => c.generated))
  ) {
    parts.push(`PRIMARY KEY (${descriptor.primary_key.map(quote).join(", ")})`);
  }
  return `CREATE TABLE ${quote(descriptor.table_id)} (${parts.join(", ")})${
    backend === "sqlite" ? " STRICT" : ""
  }`;
}
export const createIndexSQL = (table: string, index: IndexDescriptor) =>
  `CREATE ${index.unique ? "UNIQUE " : ""}INDEX IF NOT EXISTS ${
    quote(index.name)
  } ON ${quote(table)} (${index.columns.map(quote).join(", ")})`;

export function validateEvaluatedTable(table: EvaluatedTable): void {
  const d = table.descriptor;
  if (
    !d || d.format_version !== 1 || typeof d.table_id !== "string" ||
    !validTable(d.table_id) || !Array.isArray(d.columns) || !d.columns.length ||
    (d.primary_key != null && !Array.isArray(d.primary_key)) ||
    (d.indexes != null && !Array.isArray(d.indexes))
  ) {
    throw new TypeError("invalid table descriptor");
  }
  const encoded = JSON.parse(table.descriptor_json);
  // JSON transports may reorder object keys. Authored array order and the
  // evaluator's exact serialized bytes/hash remain significant.
  if (
    JSON.stringify(encoded) !== table.descriptor_json ||
    !isDeepStrictEqual(JSON.parse(JSON.stringify(d)), encoded)
  ) {
    throw new TypeError("descriptor JSON does not match the descriptor");
  }
  if (hash(table.descriptor_json) !== table.descriptor_hash) {
    throw new TypeError("descriptor hash does not match descriptor JSON");
  }
  const names = new Set<string>();
  const primary = new Set(d.primary_key ?? []);
  if (primary.size !== (d.primary_key ?? []).length) {
    throw new TypeError("duplicate primary-key column");
  }
  for (const c of d.columns) {
    if (
      !c || typeof c.name !== "string" || typeof c.logical_type !== "string" ||
      [c.nullable, c.generated, c.primary_key, c.unique].some((value) =>
        typeof value !== "boolean"
      )
    ) {
      throw new TypeError("invalid column descriptor");
    }
    if (
      !validColumn(c.name) ||
      ["table", "select", "selectAll", "insert", "update", "delete"].includes(
        c.name,
      ) || names.has(c.name)
    ) throw new TypeError(`invalid or duplicate column ${c.name}`);
    names.add(c.name);
    if (c.primary_key !== primary.has(c.name)) {
      throw new TypeError(
        `primary-key metadata disagrees for column ${c.name}`,
      );
    }
    physicalType("sqlite", c);
    if (c.primary_key && c.nullable) {
      throw new TypeError("primary-key columns cannot be nullable");
    }
    if (
      c.generated &&
      (c.default || c.logical_type !== "integer" || !c.primary_key ||
        primary.size !== 1)
    ) {
      throw new TypeError(
        "generated column must be the single integer primary key without a default",
      );
    }
    if (c.logical_type === "enum") normalizedEnumValues(c.enum_values!);
    else if (c.enum_values?.length) {
      throw new TypeError("enum values are valid only for enum columns");
    }
    if (c.logical_type !== "decimal" && (c.precision || c.scale)) {
      throw new TypeError(
        "precision and scale are valid only for decimal columns",
      );
    }
    if (
      c.reference &&
      (!validTable(c.reference.table) || !validColumn(c.reference.column))
    ) throw new TypeError("invalid logical reference");
    if (!c.default) continue;
    if (c.default.kind === "now") {
      if (c.logical_type !== "datetime" || c.default.value !== undefined) {
        throw new TypeError("defaultNow() is valid only for datetime columns");
      }
      continue;
    }
    if (c.default.kind !== "literal") {
      throw new TypeError("invalid default kind");
    }
    const v = c.default.value;
    switch (c.logical_type) {
      case "text":
        if (typeof v !== "string") {
          throw new TypeError("text default must be a string");
        }
        break;
      case "enum":
        if (typeof v !== "string" || !c.enum_values!.includes(v)) {
          throw new TypeError("enum default must be a declared value");
        }
        break;
      case "boolean":
        if (typeof v !== "boolean") {
          throw new TypeError("boolean default must be a boolean");
        }
        break;
      case "integer":
        assertSafeInteger(v);
        break;
      case "float":
        assertFiniteFloat(v);
        break;
      case "decimal":
        if (typeof v !== "string") {
          throw new TypeError("decimal default must be a canonical string");
        }
        decimalToScaled(v, c.precision!, c.scale ?? 0);
        break;
      case "datetime":
        if (
          typeof v !== "string" ||
          !/^\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d(?:\.\d{1,3})?Z$/.test(v) ||
          !Number.isFinite(Date.parse(v)) ||
          new Date(v).toISOString().slice(0, 19) !== v.slice(0, 19)
        ) {
          throw new TypeError(
            "datetime default must be UTC with millisecond precision",
          );
        }
        break;
      case "bytes":
        if (typeof v !== "string") {
          throw new TypeError("bytes default must be base64");
        }
        base64ToBytes(v);
        break;
      case "json":
        if (v === undefined) throw new TypeError("JSON default is invalid");
        JSON.stringify(v);
        break;
    }
  }
  for (const name of primary) {
    if (!names.has(name)) {
      throw new TypeError(`primary key references unknown column ${name}`);
    }
  }
  const indexes = new Set<string>();
  for (const index of d.indexes ?? []) {
    if (
      !index || typeof index.name !== "string" ||
      typeof index.unique !== "boolean" || !Array.isArray(index.columns) ||
      !validColumn(index.name) || !index.columns.length ||
      indexes.has(index.name)
    ) throw new TypeError("invalid index descriptor");
    indexes.add(index.name);
    if (
      new Set(index.columns).size !== index.columns.length ||
      index.columns.some((c) => !names.has(c))
    ) {
      throw new TypeError(
        `index ${index.name} references unknown or duplicate column`,
      );
    }
  }
}
const normalizeType = (v: string) =>
  v.trim().toLowerCase().replace(/\s+/g, " ");
function normalizeDefault(v: string): string {
  v = normalizeType(v);
  while (v.startsWith("(") && v.endsWith(")")) v = v.slice(1, -1).trim();
  return v;
}
function defaultMatches(
  backend: Backend,
  c: ColumnDescriptor,
  actual: string,
): boolean {
  if (c.generated) return true;
  if (!c.default) return !actual.trim();
  if (!actual.trim()) return false;
  const want = normalizeDefault(defaultSQL(backend, c)),
    found = normalizeDefault(actual);
  if (
    want === found ||
    (backend === "postgresql" && found.startsWith(`${want}::`))
  ) return true;
  return c.default.kind === "now" &&
    (found.includes("current_timestamp") || found.includes("now()") ||
      (backend === "sqlite" && found.includes("strftime(") &&
        found.includes("'now'")));
}
export function compareColumn(
  backend: Backend,
  expected: ColumnDescriptor,
  actual: PhysicalColumn,
): string[] {
  const differences: string[] = [],
    name = expected.name,
    type = physicalType(backend, expected);
  if (normalizeType(actual.type) !== normalizeType(type)) {
    differences.push(`column ${name} type is ${actual.type}; expected ${type}`);
  }
  if (actual.nullable !== expected.nullable && !expected.primary_key) {
    differences.push(`column ${name} nullability differs`);
  }
  if (actual.primary_key !== expected.primary_key) {
    differences.push(`column ${name} primary key differs`);
  }
  if (expected.generated && !actual.generated) {
    differences.push(`column ${name} generated identity is missing`);
  }
  if (backend === "postgresql" && !expected.generated && actual.generated) {
    differences.push(`column ${name} has an unexpected generated identity`);
  }
  if (!defaultMatches(backend, expected, actual.default)) {
    differences.push(`column ${name} default differs`);
  }
  return differences;
}
export function comparePhysical(
  backend: Backend,
  d: TableDescriptor,
  physical: PhysicalColumn[],
): string[] {
  const actual = new Map(physical.map((c) => [c.name, c]));
  return d.columns.flatMap((c) => {
    const found = actual.get(c.name);
    if (!found) return [`missing column ${c.name}`];
    const differences = compareColumn(backend, c, found);
    if (
      c.primary_key &&
      found.primary_key_position !== d.primary_key.indexOf(c.name) + 1
    ) {
      differences.push(
        `column ${c.name} primary-key position is ${found.primary_key_position}; expected ${
          d.primary_key.indexOf(c.name) + 1
        }`,
      );
    }
    return differences;
  });
}
export function compareIndexes(
  expected: IndexDescriptor[],
  physical: PhysicalIndex[],
  ignored: Set<string>,
): string[] {
  const actual = new Map(physical.map((i) => [i.name, i])),
    differences: string[] = [];
  for (const index of expected) {
    const found = actual.get(index.name);
    if (!found) differences.push(`missing index ${index.name}`);
    else if (
      found.unique !== index.unique ||
      JSON.stringify(found.columns) !== JSON.stringify(index.columns)
    ) differences.push(`index ${index.name} definition differs`);
    actual.delete(index.name);
  }
  for (const [name, index] of actual) {
    if (!index.columns.length || !index.columns.every((c) => ignored.has(c))) {
      differences.push(`unexpected index ${name}`);
    }
  }
  return differences.sort();
}
export function compareChecks(
  backend: Backend,
  d: TableDescriptor,
  physical: string[],
  ignored: Set<string>,
): string[] {
  const actual = new Set(physical), differences: string[] = [];
  for (const c of d.columns) {
    if (!checkExpression(backend, c)) continue;
    const name = checkName(d.table_id, c.name);
    if (!actual.delete(name)) {
      differences.push(`missing check constraint ${name}`);
    }
  }
  for (const name of actual) {
    if (![...ignored].some((c) => checkName(d.table_id, c) === name)) {
      differences.push(`unexpected check constraint ${name}`);
    }
  }
  return differences.sort();
}
