import { assertEquals, assertThrows } from "@std/assert";
import {
  columnSQL,
  compareColumn,
  createTableSQL,
  defaultSQL,
  hash,
  physicalType,
  validateEvaluatedTable,
} from "./ddl.ts";
import type { ColumnDescriptor, LogicalType } from "../src/schema.ts";
import type { EvaluatedTable } from "./evaluator.ts";

import { kernelDatabaseBackendSymbol } from "@the8020/kernel";
(globalThis as unknown as Record<symbol, unknown>)[
  kernelDatabaseBackendSymbol
] = "sqlite";
const { table, t } = await import("../mod.ts");
const { descriptorOf } = await import("../src/descriptor.ts");

Deno.test("schema SQL preserves both engines' logical storage and constraints", () => {
  const column = (logical_type: LogicalType): ColumnDescriptor => ({
    name: "value",
    logical_type,
    precision: logical_type === "decimal" ? 18 : undefined,
    scale: logical_type === "decimal" ? 2 : undefined,
    nullable: false,
    primary_key: false,
    generated: false,
    unique: false,
  });
  const mappings: Array<[LogicalType, string, string]> = [
    ["text", "TEXT", "text"],
    ["boolean", "INTEGER", "boolean"],
    ["integer", "INTEGER", "bigint"],
    ["float", "REAL", "double precision"],
    ["decimal", "INTEGER", "bigint"],
    ["datetime", "TEXT", "timestamp with time zone"],
    ["bytes", "BLOB", "bytea"],
    ["json", "TEXT", "jsonb"],
  ];
  for (const [logical, sqlite, postgres] of mappings) {
    assertEquals(physicalType("sqlite", column(logical)), sqlite);
    assertEquals(physicalType("postgresql", column(logical)), postgres);
  }
  const decimal = {
    ...column("decimal"),
    default: { kind: "literal" as const, value: "9999999999999999.99" },
  };
  for (const backend of ["sqlite", "postgresql"] as const) {
    assertEquals(defaultSQL(backend, decimal), "999999999999999999");
    assertEquals(
      columnSQL(backend, "acme__orders__orders", decimal, true).includes(
        "BETWEEN -999999999999999999 AND 999999999999999999",
      ),
      true,
    );
  }
  assertEquals(
    defaultSQL("postgresql", {
      ...column("datetime"),
      default: { kind: "now" },
    }),
    "date_trunc('milliseconds', CURRENT_TIMESTAMP)",
  );
  assertThrows(
    () =>
      columnSQL("sqlite", "acme__orders__orders", {
        ...column("datetime"),
        default: { kind: "now" },
      }, false),
    Error,
    "requires a migration",
  );
});

Deno.test("schema validation verifies the actual descriptor, hash, enum and references", () => {
  const descriptor = descriptorOf(
    table("acme__ddl__sample", {
      id: t.integer().primaryKey().generated(),
      state: t.enum(["draft", "done"]),
      payload: t.json().default({ markup: "<strong>&</strong>" }),
    }),
  );
  const evaluated = (d = descriptor): EvaluatedTable => {
    const json = JSON.stringify(d);
    return {
      descriptor: d,
      descriptor_json: json,
      descriptor_hash: hash(json),
      source_module: "/workspace/packages/acme/ddl/tables/sample.ts",
      source_package: "acme/ddl",
      source_commit: "one",
      dependencies: [],
    };
  };
  validateEvaluatedTable(evaluated());
  const transported = evaluated();
  transported.descriptor = JSON.parse(
    JSON.stringify(
      descriptor,
      (_key, value) =>
        value && typeof value === "object" && !Array.isArray(value)
          ? Object.fromEntries(
            Object.entries(value).sort(([a], [b]) => a.localeCompare(b)),
          )
          : value,
    ),
  );
  validateEvaluatedTable(transported);
  assertThrows(
    () =>
      validateEvaluatedTable({
        ...transported,
        descriptor: { ...transported.descriptor, table_id: "acme__ddl__other" },
      }),
    TypeError,
    "does not match",
  );
  assertThrows(
    () =>
      validateEvaluatedTable(
        evaluated({
          ...descriptor,
          columns: descriptor.columns.map((c) =>
            c.name === "state"
              ? { ...c, nullable: "yes" as unknown as boolean }
              : c
          ),
        }),
      ),
    TypeError,
    "invalid column descriptor",
  );
  assertEquals(createTableSQL("sqlite", descriptor).endsWith(" STRICT"), true);
  assertEquals(
    createTableSQL("postgresql", descriptor).includes(
      "GENERATED BY DEFAULT AS IDENTITY",
    ),
    true,
  );
  assertThrows(
    () =>
      validateEvaluatedTable({ ...evaluated(), descriptor_hash: "invalid" }),
    TypeError,
    "hash",
  );
  assertThrows(
    () =>
      validateEvaluatedTable(
        evaluated({
          ...descriptor,
          columns: descriptor.columns.map((c) =>
            c.name === "state" ? { ...c, enum_values: ["draft", "draft"] } : c
          ),
        }),
      ),
    TypeError,
    "unique",
  );
  assertThrows(
    () =>
      validateEvaluatedTable(
        evaluated({
          ...descriptor,
          columns: descriptor.columns.map((c) =>
            c.name === "state"
              ? { ...c, reference: { table: "invalid", column: "id" } }
              : c
          ),
        }),
      ),
    TypeError,
    "reference",
  );
  const expected = descriptor.columns[0]!;
  assertEquals(
    compareColumn("postgresql", expected, {
      name: "id",
      type: "bigint",
      nullable: false,
      default: "",
      primary_key: true,
      primary_key_position: 1,
      generated: false,
    }),
    ["column id generated identity is missing"],
  );
});
